### ISSUE TITLE
Improvements to jmxtrans chef-cookbook?

### ISSUE THREAD

**Issue by solarce** [jmxtrans/jmxtrans#180]
I recently forked, https://github.com/solarce/chef-jmxtrans,  and am working on updating the chef cookbook for jmxtrans, as I'm deploying it in production. 

I thought I'd open an issue to invite folks who might be interested in using the cookbook to open issues on my fork for improvements they might like to see, I'm gonna file issues next week for further improvements I want to make.

**Comment by gehel** [comment]
While having a chef cookbook for JmxTrans is a great idea (and thanks a lot for contributing to it), this cookbook is not managed by the core JmxTrans team. And this issue is more an information than an actual issue. I invite you to drop in the [JmxTrans Goolgle group](https://groups.google.com/forum/#!forum/jmxtrans), or our [Gitter chat](https://gitter.im/jmxtrans/jmxtrans) every now and then to see if anyone is interested.

If there are no objections, I'm going to close this soon.

**Comment by zarry** [comment]
It would be cool if we could standardize on a single cookbook repo for jmxtrans.  It looks like there are 3-4 active forks right now and I am just starting to leverage jmxtrans and not sure which to get behind.

**Comment by bijugs** [comment]
@zarry .. if it is of any help... [our cookbook]( https://github.com/bijugs/jmxtrans-cookbook) includes fixes for issues raised on original cookbook created by Bryan... and some enhancements. Also it has been running for long time in production. Hope this helps. If anything is missing in the cookbook please let us know so that we can add it to.

**Comment by zarry** [comment]
@bijugs I actually am working with your cookbook in vagrant now.  I initially ran into issues on the JPS exec block as it couldn't find JPS.  It is not clear that java needs to be installed indepedntly on the machine from the documentation. I installed java and was able to get past that.  I will continue working with the cookbook to get it to do something aside form converge but so far it is looking like the most stable/working fork. 

@solarce your cookbook off of master would not unzip the jmxtrans package as the /opt/jmxtrans directory didn't exist(but it actually did and the permissions looked correct). I put that one aside to explore other forks in the mean time.

**Comment by bijugs** [comment]
@zarry. Thanks for the feedback. Do you mind raising an issue and I will fix it. It will also help tracking the issue in the correct repo and @gehel can close this item.

**Comment by lookfirst** [comment]
@bijugs If there is a good cookbook that is maintained, can we bring it under the jmxtrans github organization? we will give you commit access, etc. it would just be nice for end users to not have to go digging around for this. it would also be nice to document it in a central spot. =)

**Comment by bijugs** [comment]
@lookfirst, I don't see any reasons not to do it and it will help users of JMXTrans to go to a single place as you mentioned.

**Comment by lookfirst** [comment]
@bijugs sweet. welcome to the fold. i think you just need to initiate a transfer request in the admin for your project.

**Comment by zarry** [comment]
You should also work on getting a version up on https://supermarket.chef.io.  The current version up there appears to be quite old at this point.  That is a common place people search initially for finding cookbooks to use.

**Comment by lookfirst** [comment]
Woah. [`1,013,461 TOTAL DOWNLOADS`](https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=jmxtrans)

**Comment by zarry** [comment]
@lookfirst not so fast... There is a bug in older versions of the berkshelf api server that each time it polls supermarket it triggers a "download" even though the cookbook wasn't actually downloaded.

**Comment by lookfirst** [comment]
lol. yea, i figured the numbers were incorrect.

**Comment by bijugs** [comment]
@lookfirst . I am trying to transfer the `` jmxtrans-cookbook `` repo to `` jmxtrans `` and receiving the error 
```
You don't have admin rights to jmxtrans
```
Based on the [github docs](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization), my user-id need to have ``admin`` access in ``jmxtrans`` org during the transfer process. Can we coordinate this so that the transfer can be completed and the ``admin`` rights can be revoked once the transfer is complete.

**Comment by lookfirst** [comment]
I created a new team with admin access and added you to it. Hopefully that works now?

**Comment by bijugs** [comment]
@lookfirst Thanks!! The move is complete.

**Comment by lookfirst** [comment]
@bijugs Looks great! Thanks so much and welcome to the team.

**Comment by lookfirst** [comment]
I'm going to close this issue as further issues can be filed in the cookbook now.

**Comment by gehel** [comment]
I need to publish the same for Puppet ... I'm adding this to my internal todo list ...
