### ISSUE TITLE
is it possible to connect JVM in localhost without configure port?

### ISSUE THREAD

**Issue by fudy** [jmxtrans/jmxtrans#339]
in Jconsole, I can connect my localhost JVM without knowing the port.
I know If I can add the following JVM parameter to start the java application.
-Dcom.sun.management.jmxremote.port=7000

but, is it possible to connect java application without port in localhost?

**Comment by gehel** [comment]
In the current implementation of JMXTrans, no, it is not possible. It should be feasible to attach to the process to monitor directly, but that would require to pass the PID of the process instead of the port, so no real gain here. If you want to implement this feature, feel free to send a pull request!

I'm closing this as I think the question is answered. Feel free to re open or to hit the [Google group](groups.google.com/forum/#!forum/jmxtrans) to continue the discussion.

**Comment by fudy** [comment]
thanks for your answer

**Comment by gehel** [comment]
no problem !

**Comment by cyrille-leclerc** [comment]
Hi @fudy,

Did you see @pingtimeout's recent contribution to jmxtrans-agent? "support for dynamic agent attachment".

https://github.com/jmxtrans/jmxtrans-agent/releases/tag/jmxtrans-agent-1.2.0
