### ISSUE TITLE
JmxTransModule.class in last several builds is out of sync with github.

### ISSUE THREAD

**Issue by ryanstull** [jmxtrans/jmxtrans#428]
I'm trying to use JmxTrans and I was going through the example to connect with ActiveMQ when I noticed I got the error...

"The method createInjector(JmxTransConfiguration) is undefined for the type JmxTransModule"

I investigated a bit and found that the version of JmxTransModule in the last few builds (I checked 252 and 253) is not in sync with what's on Github. 

Here are the differences.

[JmxTransModule (Github)](https://github.com/jmxtrans/jmxtrans/files/164076/JmxTransModule.Github.txt)
[JmxTransModule (253 build)](https://github.com/jmxtrans/jmxtrans/files/164077/JmxTransModule.253.build.txt)

I'm not sure if there are any other files that are different but seeing as this one is different, there many be more.

**Comment by gehel** [comment]
Yes, there are quite a few commits since the last release. Maybe it is time for a new release...

If you want the latest SNAPSHOTs have a look at the [SNAPSHOT repository](https://oss.sonatype.org/content/repositories/snapshots/org/jmxtrans/jmxtrans-parent/).

So yes, release are out of sync with the HEAD of master, that's what is expected. If you find difference between the tag [`jmxtrans-parent-253`](https://github.com/jmxtrans/jmxtrans/tree/jmxtrans-parent-253) and the release 253, let me know, that would be something seriously wrong...

That being said, feel free to open an issue for your injector problem (there is not enough context here for me to understand what's going wrong) or contact the [Google group](https://groups.google.com/forum/#!forum/jmxtrans).

**Comment by ryanstull** [comment]
Ah I see, I was using the 253 release and looking at the most current example files.  Problem solved, thanks!
