### ISSUE TITLE
Make XXXWriter Pool configurable

### ISSUE THREAD

**Issue by hgomez** [jmxtrans/jmxtrans#432]
It would be nice to have more control of Writers Pool, ie GraphiteWriterFactory.
When moving from GraphiteWriter to GraphiteWriterFactory, I noticed 60 establissed connections instead of 5/6, and it may be too high.

Ad minima, we should be able to configure 

- Pool Size
- Max Idle
- Min Idle

**Comment by gehel** [comment]
Strange, strange, strange... The pool of TCP connections used by [GraphiteWriterFactory has a size of 1](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/TcpOutputWriterBuilder.java#L54) (it still make sense to make it configureable). The issue is probably that multiple instances of GraphiteWriter2 are created. [ServerListBuilder](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/ServerListBuilder.java) should take care of reusing the same instance (as long as its parameters are the same).

It looks like there is a bug just as much as a new feature request.
