### ISSUE TITLE
ResultTransformerOutputWriter - Not stopped/cleaned up

### ISSUE THREAD

**Issue by willmpls** [jmxtrans/jmxtrans#500]
I'm working on a UDP/TCP output for InfluxDB line protocol, and noticed that when using the ResultTransformerOutputWriter along with a single output defined at the server level I accumulate open TCP or UDP ports as I add or update new config files faster than I should.  

Root cause is that the writers aren't being cleaned up, so open ports continue to pile up until jmxtrans is restarted.

This behavior appears to be due to the following:
- JMXTransformer only loops and calls stop() on writers defined in queries, not servers.
- ResultTransformerOutputWriter doesn't implement the stop() method 

The following diff shows updates I made which fix the issue in my case, but I wanted to get thoughts on implementation before submitting a pr:

https://github.com/jmxtrans/jmxtrans/compare/master...willmpls:output_writer_stop

**Comment by gehel** [comment]
This is definitely a bug. [OutputWriter](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/model/OutputWriter.java) should extend [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) instead of declaring a specific `close()` method, and obviously, all output writers should take care of cleaning their resources.

Thanks for spotting that!

**Comment by gehel** [comment]
Your proposed change looks good. Minor comment: I would let the exception bubble up in [`ResultTransformerOutputWriter.close`](https://github.com/jmxtrans/jmxtrans/compare/master...willmpls:output_writer_stop#diff-5e0b720cd7f46e983925f01c06b45470R77) instead of logging it.

**Comment by gehel** [comment]
Closing this as it should be fixed by #503
