### ISSUE TITLE
Different builds

### ISSUE THREAD

**Issue by YouriAndropov** [jmxtrans/jmxtrans#620]
Hello, I couldn't find any info about different builds like jmxtrans.jar, jmxtrans-all.jar, jmxtrans-dist.jar.
What are the differences between those builds ?

**Comment by gehel** [comment]
Those are different artifacts of the same build (well, at least in maven terminology). Best place to look is the  [jmxtrans pom itself](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans/pom.xml) (but it is a bit convoluted). We have a bunch of crap leftover from earlier times. And some duplication because not all packaging have been aligned.

**Comment by YouriAndropov** [comment]
Ok but which one should I download ? jmxtrans-all ? I need a tar.gz distro, not a package.

**Comment by gehel** [comment]
In that case, you probably want the jmxtrans-all.jar. It contains all the classes required to run jmxtrans. You can execute it simply with `java -jar jmxtrans-all.jar <whatever options>`.

**Comment by gehel** [comment]
Closing this, feel free to re-open if you need more infos
